version: '3'
services:
  db:
    image: postgres:16-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: split_wine
      POSTGRES_PASSWORD: split_wine
      POSTGRES_DB: split_wine