openapi: 3.1.0
servers:
  - url: https://split-wine.onrender.com
info:
  description: >-
    SPLIT WINE!!!!!
  version: 1.0.0
  title: Split Wine API
tags:
  - name: user
    description: Operations about user
paths:
  /users:
    get:
      tags:
        - user
      summary: (temp) get all users
      description: temporary endpoint as a demo
      operationId: getUsers
      responses:
        '200':
          description: TODO
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
                
externalDocs:
  description: TODO
  url: TODO
components:
  requestBodies: {}
  schemas:
    User:
      title: User
      description: A user
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string
          format: email
        password:
          type: string
          format: password
      required: 
        - name
        - email
        - password