name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: cd backend
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: backend/.nvmrc
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json
    - run: npm install
    - run: yarn
    - run: yarn lint
    - run: yarn run test
  backend-e2e-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: cd backend
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: backend/.nvmrc
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json
    - run: npm install
    - run: yarn
    - run: yarn lint
    - run: yarn test:e2e
    - run: yarn test:infra:down
  frontend-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v3
      - run: cd frontend
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - run: yarn
      - run: yarn lint
      - run: yarn run test