name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: cd backend
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: backend/.nvmrc
        cache: 'npm'
        cache-dependency-path: backend/yarn.lock
    - name: yarn install yarn lint and run test
      working-directory: ./backend
      run: yarn && yarn lint && yarn run test
  backend-e2e-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: backend/.nvmrc
        cache: 'npm'
        cache-dependency-path: backend/yarn.lock
    - name: yarn run e2e test
      working-directory: ./backend
      run: yarn && yarn lint && yarn test:e2e && yarn test:infra:down
  frontend-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v3
      - run: cd frontend
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: frontend/yarn.lock
      - name: yarn && yarn lint && yarn run test
        working-directory: ./frontend
        run: yarn && yarn lint && yarn run test